apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-chart.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "python-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      nodePort: {{ .Values.service.nodeport }}